apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: demowebapp
  name: demowebapp
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: demowebapp
    spec:
      containers:
      - image: shilpa21/demo
        name: demowebapp
        ports:
        - name: demowebapp
          containerPort: 8080  
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: demowebapp
  name: demowebapp
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: demowebapp