apiVersion: v1
kind: POD
metadata:
  name: demo
  labels:
    app: demoapp
spec:
  containers:
    - name: democontainer
	  image: shilpa21/demo


-----------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
	  app: demoapp
  template:
    metadata:
      name: demopod
      labels:
        app: demoapp
    spec:
      containers:
        - name: democontainer
	      image: shilpa21/demo
		  ports:
		    - containerPort:8080


---------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: demoapp
spec:
  selector:
    app: demoapp
  ports:
  - port: 80
    targetPort: 8080
  type: NodePort
	